language: go
go: 1.4
python: 2.7

before_install:
  - mkdir -p $HOME/gopath/src/sourcegraph.com/sourcegraph
  - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/sourcegraph.com/sourcegraph/srclib
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/sourcegraph.com/sourcegraph/srclib
  # for rst2html (package doc)
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-docutils
  - export PATH=$PATH:$HOME/gopath/bin
  - export GOBIN=$HOME/gopath/bin
  - sudo pip install virtualenv

install:
  - go get -d -v ./... && go build -v ./...
  - go install ./cmd/src

script:
  - go test -v ./...
  - make install-std-toolchains
  - make test-std-toolchains

