site_name: srclib
site_description: srclib is a hackable, polyglot code analysis library.

docs_dir: sources

repo_url: https://sourcegraph.com/sourcegraph/srclib/

dev_addr: '0.0.0.0:8000'

theme_dir: ./theme/

google_analytics: ['UA-40540747-5', 'srclib.org']

toolchains:
- lang: Go
  repo: srclib/srclib-go
- lang: Java
  repo: srclib/srclib-java

commands:
- command: 'src api describe'
  type: APIDescribeCmd
- command: 'src api list'
  type: APIListCmd
- command: 'src api deps'
  type: APIDepsCmd
- command: 'src api units'
  type: APIUnitsCmd

pages:

- ['overview.md', 'Overview']
- ['install.md', 'Installation']

# Editor plugins
- ['plugins/emacs.md', 'Editor plugins', 'Emacs']
- ['plugins/sublimetext.md', 'Editor plugins', 'Sublime Text']
- ['plugins/vim.md', 'Editor plugins', 'Vim']
- ['plugins/atom.md', 'Editor plugins', 'Atom']
- ['plugins/creatingaplugin.md', 'Editor plugins', 'Creating a Plugin']

# Language toolchains
- ['toolchains/overview.md', 'Language toolchains', 'Overview']
- ['toolchains/python.md', 'Language toolchains', 'Python']
- ['toolchains/go.md', 'Language toolchains', 'Go']
- ['toolchains/ruby.md', 'Language toolchains', 'Ruby']
- ['toolchains/javascript.md', 'Language toolchains', 'JavaScript']
- ['toolchains/java.md', 'Language toolchains', 'Java']
- ['toolchains/haskell.md', 'Language toolchains', 'Haskell']
- ['toolchains/php.md', 'Language toolchains', 'PHP']
#- ['toolchains/creatingatoolchain.md', 'Language toolchains', 'Creating a Toolchain']
- ['toolchains/faq.md', 'Language toolchains', 'FAQ']

# Building
#- ['building/uploading.md', 'Library Authors', 'Uploading to Sourcegraph']

# src API
- ['api/overview.md', 'src API', 'Overview']
- ['api/make.md', 'src API', 'src make']

# Schema
- ['api/data-model.md', 'Schema', 'Overview']
- ['toolchains/commonstructures.md', 'Schema', 'Common Data Structures']
- ['toolchains/scanner-output.md', 'Schema', 'Scanner Output']
- ['toolchains/grapher-output.md', 'Schema', 'Grapher Output']
- ['toolchains/dependency-resolution-output.md', 'Schema', 'Dependency Resolution Output']

# Contributing
#- ['contributing.md', 'Contributing']

